# Site settings
title: Michael Ion
email: michael.antonius.ion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Ion. Austria, Vienna
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelion.net" # the base hostname & protocol for your site
linkedin_username: "michael-ion"
github_username:  "mionisation"
permalink:    /:year/:title

# Build settings
markdown: kramdown

#Plug-ins
gems: [jekyll/footnotes]
